#index:
#    path: /
#    controller: App\Controller\DefaultController::index
master:
    type: rest
    resource: App\Controller\MasterController
    prefix : /api

creditcard:
    type: rest
    resource: App\Controller\CreditcardController
    prefix : /api

company:
    type: rest
    resource: App\Controller\CompanyController
    prefix : /api

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
